# Generated by Django 4.0.6 on 2022-08-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_thirdparty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='Symbol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
